// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestScheduler.Data;

namespace TestScheduler.Migrations
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestScheduler.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Level = "Level 5",
                            Module_Code = "BI100100",
                            Module_Description = "D101 Programming Fundamentals"
                        },
                        new
                        {
                            ID = 2,
                            Level = "Level 5",
                            Module_Code = "BI100101",
                            Module_Description = "D111 Data Fundamentals"
                        },
                        new
                        {
                            ID = 3,
                            Level = "Level 5",
                            Module_Code = "BI100101",
                            Module_Description = "D111 Database Fundamentals"
                        },
                        new
                        {
                            ID = 4,
                            Level = "Level 5",
                            Module_Code = "BI100103",
                            Module_Description = "I102 Technical Support Fundamentals"
                        },
                        new
                        {
                            ID = 5,
                            Level = "Level 5",
                            Module_Code = "BI100104",
                            Module_Description = "I111 Web Fundamentals"
                        },
                        new
                        {
                            ID = 6,
                            Level = "Level 5",
                            Module_Code = "BI100105",
                            Module_Description = "I121 Systems Analysis Fundamentals"
                        },
                        new
                        {
                            ID = 7,
                            Level = "Level 5",
                            Module_Code = "BI100106",
                            Module_Description = "T101 Network Fundamentals"
                        },
                        new
                        {
                            ID = 8,
                            Level = "Level 5",
                            Module_Code = "BI100107",
                            Module_Description = "T111 Computer Fundamentals"
                        },
                        new
                        {
                            ID = 9,
                            Level = "Level 5",
                            Module_Code = "BI100107",
                            Module_Description = "T111 Computer Hardware Fundamentals"
                        },
                        new
                        {
                            ID = 10,
                            Level = "Level 5",
                            Module_Code = "BI100108",
                            Module_Description = "I101 Information Systems"
                        },
                        new
                        {
                            ID = 11,
                            Level = "Level 5",
                            Module_Code = "BI100108",
                            Module_Description = "I101 Information Systems Fundamentals"
                        },
                        new
                        {
                            ID = 12,
                            Level = "Level 6",
                            Module_Code = "BI200201",
                            Module_Description = "I202 IT Project Management"
                        },
                        new
                        {
                            ID = 13,
                            Level = "Level 6",
                            Module_Code = "BI200202",
                            Module_Description = "D211 Database Development"
                        },
                        new
                        {
                            ID = 14,
                            Level = "Level 6",
                            Module_Code = "BI200203",
                            Module_Description = "I221 Analysis and Design"
                        },
                        new
                        {
                            ID = 15,
                            Level = "Level 6",
                            Module_Code = "BI200204",
                            Module_Description = "D201 Advanced Programming"
                        },
                        new
                        {
                            ID = 16,
                            Level = "Level 6",
                            Module_Code = "BI200205",
                            Module_Description = "D202 Software Process"
                        },
                        new
                        {
                            ID = 17,
                            Level = "Level 6",
                            Module_Code = "BI200206",
                            Module_Description = "I211 eCommerce Systems"
                        },
                        new
                        {
                            ID = 18,
                            Level = "Level 6",
                            Module_Code = "BI200207",
                            Module_Description = "I213 Dynamic Web Solutions"
                        },
                        new
                        {
                            ID = 19,
                            Level = "Level 6",
                            Module_Code = "BI200208",
                            Module_Description = "T201 Network Services"
                        },
                        new
                        {
                            ID = 20,
                            Level = "Level 6",
                            Module_Code = "BI200211",
                            Module_Description = "T211 Systems Security"
                        },
                        new
                        {
                            ID = 21,
                            Level = "Level 6",
                            Module_Code = "BI200212",
                            Module_Description = "I203 Digital Multimedia"
                        },
                        new
                        {
                            ID = 22,
                            Level = "Level 6",
                            Module_Code = "BI200213",
                            Module_Description = "T205 Networks (Cisco ITN)"
                        },
                        new
                        {
                            ID = 23,
                            Level = "Level 6",
                            Module_Code = "BI200214",
                            Module_Description = "T206 Networks (Cisco RSE)"
                        },
                        new
                        {
                            ID = 24,
                            Level = "Level 6",
                            Module_Code = "BI200215",
                            Module_Description = "I209 Industry Placement"
                        },
                        new
                        {
                            ID = 25,
                            Level = "Level 6",
                            Module_Code = "BI200216",
                            Module_Description = "I212 Enterprise Data Management"
                        },
                        new
                        {
                            ID = 26,
                            Level = "Level 6",
                            Module_Code = "BI200217",
                            Module_Description = "I263 Introduction to Finance"
                        },
                        new
                        {
                            ID = 27,
                            Level = "Level 7",
                            Module_Code = "BI200250",
                            Module_Description = "Elective A"
                        },
                        new
                        {
                            ID = 28,
                            Level = "Level 7",
                            Module_Code = "BI200251",
                            Module_Description = "Elective B"
                        },
                        new
                        {
                            ID = 29,
                            Level = "Level 7",
                            Module_Code = "BI300250",
                            Module_Description = "Elective C"
                        },
                        new
                        {
                            ID = 30,
                            Level = "Level 7",
                            Module_Code = "BI300251",
                            Module_Description = "Elective D"
                        },
                        new
                        {
                            ID = 31,
                            Level = "Level 7",
                            Module_Code = "BI300300",
                            Module_Description = "I301 Professional Practice"
                        },
                        new
                        {
                            ID = 32,
                            Level = "Level 7",
                            Module_Code = "BI300301",
                            Module_Description = "I302 Industry Project"
                        },
                        new
                        {
                            ID = 33,
                            Level = "Level 7",
                            Module_Code = "BI300302",
                            Module_Description = "D301 Software Engineering"
                        },
                        new
                        {
                            ID = 34,
                            Level = "Level 7",
                            Module_Code = "BI300303",
                            Module_Description = "D303 Mobile Application Development"
                        },
                        new
                        {
                            ID = 35,
                            Level = "Level 7",
                            Module_Code = "BI300304",
                            Module_Description = "D311 Advanced Database Concepts"
                        },
                        new
                        {
                            ID = 36,
                            Level = "Level 7",
                            Module_Code = "BI300305",
                            Module_Description = "I303 Managerial Practice"
                        },
                        new
                        {
                            ID = 37,
                            Level = "Level 7",
                            Module_Code = "BI300306",
                            Module_Description = "I321 Advanced Systems Analysis"
                        },
                        new
                        {
                            ID = 38,
                            Level = "Level 7",
                            Module_Code = "BI300307",
                            Module_Description = "I3090000000Topic"
                        },
                        new
                        {
                            ID = 39,
                            Level = "Level 7",
                            Module_Code = "BI300308",
                            Module_Description = "T301 Network Design"
                        },
                        new
                        {
                            ID = 40,
                            Level = "Level 7",
                            Module_Code = "BI300309",
                            Module_Description = "T311 System Administration"
                        },
                        new
                        {
                            ID = 41,
                            Level = "Level 7",
                            Module_Code = "BI300310",
                            Module_Description = "T302 Cisco Scaling and Connecting Networks"
                        },
                        new
                        {
                            ID = 42,
                            Level = "Level 7",
                            Module_Code = "BI300312",
                            Module_Description = "I304 Data Analytics and Intelligence"
                        },
                        new
                        {
                            ID = 43,
                            Level = "Level 7",
                            Module_Code = "BI300313",
                            Module_Description = "I311 Advanced Web Solutions"
                        },
                        new
                        {
                            ID = 44,
                            Level = "Level 7",
                            Module_Code = "BI300314",
                            Module_Description = "I367 Advanced Project Management"
                        },
                        new
                        {
                            ID = 45,
                            Level = "Level 7",
                            Module_Code = "BI300315",
                            Module_Description = "T312 Network Security"
                        },
                        new
                        {
                            ID = 46,
                            Level = "Level 5",
                            Module_Code = "BI100100",
                            Module_Description = "D101 Programming Fundamentals"
                        },
                        new
                        {
                            ID = 47,
                            Level = "Level 5",
                            Module_Code = "BI100101",
                            Module_Description = "D111 Data Fundamentals"
                        },
                        new
                        {
                            ID = 48,
                            Level = "Level 5",
                            Module_Code = "BI100101",
                            Module_Description = "D111 Database Fundamentals"
                        },
                        new
                        {
                            ID = 49,
                            Level = "Level 5",
                            Module_Code = "BI100103",
                            Module_Description = "I102 Technical Support Fundamentals"
                        },
                        new
                        {
                            ID = 50,
                            Level = "Level 5",
                            Module_Code = "BI100104",
                            Module_Description = "I111 Web Fundamentals"
                        },
                        new
                        {
                            ID = 51,
                            Level = "Level 5",
                            Module_Code = "BI100105",
                            Module_Description = "I121 Systems Analysis Fundamentals"
                        },
                        new
                        {
                            ID = 52,
                            Level = "Level 5",
                            Module_Code = "BI100106",
                            Module_Description = "T101 Network Fundamentals"
                        },
                        new
                        {
                            ID = 53,
                            Level = "Level 5",
                            Module_Code = "BI100107",
                            Module_Description = "T111 Computer Fundamentals"
                        },
                        new
                        {
                            ID = 54,
                            Level = "Level 5",
                            Module_Code = "BI100107",
                            Module_Description = "T111 Computer Hardware Fundamentals"
                        },
                        new
                        {
                            ID = 55,
                            Level = "Level 6",
                            Module_Code = "BI200203",
                            Module_Description = "I221AnalysisndDesign"
                        },
                        new
                        {
                            ID = 56,
                            Level = "Level 5",
                            Module_Code = "BI100108",
                            Module_Description = "I101 Information Systems"
                        },
                        new
                        {
                            ID = 57,
                            Level = "Level 5",
                            Module_Code = "BI100108",
                            Module_Description = "I101 Information Systems Fundamentals"
                        },
                        new
                        {
                            ID = 58,
                            Level = "Level 6",
                            Module_Code = "BI200201",
                            Module_Description = "I202 IT Project Management"
                        },
                        new
                        {
                            ID = 59,
                            Level = "Level 6",
                            Module_Code = "BI200203",
                            Module_Description = "I221 Analysis and Design"
                        },
                        new
                        {
                            ID = 60,
                            Level = "Level 6",
                            Module_Code = "BI200204",
                            Module_Description = "D201 Advanced Programming"
                        },
                        new
                        {
                            ID = 61,
                            Level = "Level 6",
                            Module_Code = "BI200205",
                            Module_Description = "D202 Software Process"
                        },
                        new
                        {
                            ID = 62,
                            Level = "Level 6",
                            Module_Code = "BI200206",
                            Module_Description = "I211 eCommerce Systems"
                        },
                        new
                        {
                            ID = 63,
                            Level = "Level 6",
                            Module_Code = "BI200207",
                            Module_Description = "I213 Dynamic Web Solutions"
                        },
                        new
                        {
                            ID = 64,
                            Level = "Level 6",
                            Module_Code = "BI200208",
                            Module_Description = "T201 Network Services"
                        },
                        new
                        {
                            ID = 65,
                            Level = "Level 6",
                            Module_Code = "BI200211",
                            Module_Description = "T211 Systems Security"
                        },
                        new
                        {
                            ID = 66,
                            Level = "Level 6",
                            Module_Code = "BI200212",
                            Module_Description = "I203 Digital Multimedia"
                        },
                        new
                        {
                            ID = 67,
                            Level = "Level 6",
                            Module_Code = "BI200213",
                            Module_Description = "T205 Networks (Cisco ITN)"
                        },
                        new
                        {
                            ID = 68,
                            Level = "Level 6",
                            Module_Code = "BI200214",
                            Module_Description = "T206 Networks (Cisco RSE)"
                        },
                        new
                        {
                            ID = 69,
                            Level = "Level 6",
                            Module_Code = "BI200215",
                            Module_Description = "I209 Industry Placement"
                        },
                        new
                        {
                            ID = 70,
                            Level = "Level 6",
                            Module_Code = "BI200216",
                            Module_Description = "I212 Enterprise Data Management"
                        },
                        new
                        {
                            ID = 71,
                            Level = "Level 6",
                            Module_Code = "BI200217",
                            Module_Description = "I263 Introduction to Finance"
                        },
                        new
                        {
                            ID = 72,
                            Level = "Level 6",
                            Module_Code = "BI200250",
                            Module_Description = "Elective A"
                        },
                        new
                        {
                            ID = 73,
                            Level = "Level 6",
                            Module_Code = "BI200251",
                            Module_Description = "Elective B"
                        },
                        new
                        {
                            ID = 74,
                            Level = "Level 7",
                            Module_Code = "BI300250",
                            Module_Description = "Elective C"
                        },
                        new
                        {
                            ID = 75,
                            Level = "Level 7",
                            Module_Code = "BI300251",
                            Module_Description = "Elective D"
                        },
                        new
                        {
                            ID = 76,
                            Level = "Level 7",
                            Module_Code = "BI300300",
                            Module_Description = "I301 Professional Practice"
                        },
                        new
                        {
                            ID = 77,
                            Level = "Level 7",
                            Module_Code = "BI300301",
                            Module_Description = "I302 Industry Project"
                        },
                        new
                        {
                            ID = 78,
                            Level = "Level 7",
                            Module_Code = "BI300302",
                            Module_Description = "D301 Software Engineering"
                        },
                        new
                        {
                            ID = 79,
                            Level = "Level 7",
                            Module_Code = "BI300303",
                            Module_Description = "D303 Mobile Application Development"
                        },
                        new
                        {
                            ID = 80,
                            Level = "Level 7",
                            Module_Code = "BI300304",
                            Module_Description = "D311 Advanced Database Concepts"
                        },
                        new
                        {
                            ID = 81,
                            Level = "Level 7",
                            Module_Code = "BI300305",
                            Module_Description = "I303 Managerial Practice"
                        },
                        new
                        {
                            ID = 82,
                            Level = "Level 7",
                            Module_Code = "BI300306",
                            Module_Description = "I321 Advanced Systems Analysis"
                        },
                        new
                        {
                            ID = 83,
                            Level = "Level 7",
                            Module_Code = "BI300307",
                            Module_Description = "I309 Special Topic"
                        },
                        new
                        {
                            ID = 84,
                            Level = "Level 7",
                            Module_Code = "BI300308",
                            Module_Description = "T301 Network Design"
                        },
                        new
                        {
                            ID = 85,
                            Level = "Level 5",
                            Module_Code = "BI100106",
                            Module_Description = "T101 Network Fundamentals"
                        },
                        new
                        {
                            ID = 86,
                            Level = "Level 7",
                            Module_Code = "BI300310",
                            Module_Description = "T302 Cisco Scaling and Connecting Networks"
                        },
                        new
                        {
                            ID = 87,
                            Level = "Level 7",
                            Module_Code = "BI300312",
                            Module_Description = "I304 Data Analytics and Intelligence"
                        },
                        new
                        {
                            ID = 88,
                            Level = "Level 7",
                            Module_Code = "BI300313",
                            Module_Description = "I311 Advanced Web Solutions"
                        },
                        new
                        {
                            ID = 89,
                            Level = "Level 7",
                            Module_Code = "BI300314",
                            Module_Description = "I367 Advanced Project Management"
                        },
                        new
                        {
                            ID = 90,
                            Level = "Level 7",
                            Module_Code = "BI300315",
                            Module_Description = "T312 Network Security"
                        },
                        new
                        {
                            ID = 91,
                            Level = "Level 5",
                            Module_Code = "BI100100",
                            Module_Description = "D101 Programming Fundamentals"
                        },
                        new
                        {
                            ID = 92,
                            Level = "Level 5",
                            Module_Code = "BI100101",
                            Module_Description = "D111 Data Fundamentals"
                        },
                        new
                        {
                            ID = 93,
                            Level = "Level 5",
                            Module_Code = "BI100101",
                            Module_Description = "D111 Database Fundamentals"
                        },
                        new
                        {
                            ID = 94,
                            Level = "Level 5",
                            Module_Code = "BI100103",
                            Module_Description = "I102 Technical Support Fundamentals"
                        },
                        new
                        {
                            ID = 95,
                            Level = "Level 5",
                            Module_Code = "BI100104",
                            Module_Description = "I111 Web Fundamentals"
                        },
                        new
                        {
                            ID = 96,
                            Level = "Level 5",
                            Module_Code = "BI100105",
                            Module_Description = "I121 Systems Analysis Fundamentals"
                        },
                        new
                        {
                            ID = 97,
                            Level = "Level 5",
                            Module_Code = "BI100106",
                            Module_Description = "T101 Network Fundamentals"
                        },
                        new
                        {
                            ID = 98,
                            Level = "Level 5",
                            Module_Code = "BI100107",
                            Module_Description = "T111 Computer Fundamentals"
                        },
                        new
                        {
                            ID = 99,
                            Level = "Level 5",
                            Module_Code = "BI100107",
                            Module_Description = "T111 Computer Hardware Fundamentals"
                        },
                        new
                        {
                            ID = 100,
                            Level = "Level 5",
                            Module_Code = "BI100108",
                            Module_Description = "I101 Information Systems"
                        },
                        new
                        {
                            ID = 101,
                            Level = "Level 5",
                            Module_Code = "BI100108",
                            Module_Description = "I101 Information Systems Fundamentals"
                        },
                        new
                        {
                            ID = 102,
                            Level = "Level 6",
                            Module_Code = "BI200201",
                            Module_Description = "I202 IT Project Management"
                        },
                        new
                        {
                            ID = 103,
                            Level = "Level 6",
                            Module_Code = "BI200202",
                            Module_Description = "D211 Database Development"
                        },
                        new
                        {
                            ID = 104,
                            Level = "Level 6",
                            Module_Code = "BI200203",
                            Module_Description = "I221 Analysis and Design"
                        },
                        new
                        {
                            ID = 105,
                            Level = "Level 6",
                            Module_Code = "BI200204",
                            Module_Description = "D201 Advanced Programming"
                        },
                        new
                        {
                            ID = 106,
                            Level = "Level 6",
                            Module_Code = "BI200205",
                            Module_Description = "D202 Software Process"
                        },
                        new
                        {
                            ID = 107,
                            Level = "Level 6",
                            Module_Code = "BI200206",
                            Module_Description = "I211 eCommerce Systems"
                        },
                        new
                        {
                            ID = 108,
                            Level = "Level 6",
                            Module_Code = "BI200207",
                            Module_Description = "I213 Dynamic Web Solutions"
                        },
                        new
                        {
                            ID = 109,
                            Level = "Level 6",
                            Module_Code = "BI200251",
                            Module_Description = "Elective B"
                        },
                        new
                        {
                            ID = 110,
                            Level = "Level 6",
                            Module_Code = "BI200208",
                            Module_Description = "T211 Systems Security"
                        },
                        new
                        {
                            ID = 111,
                            Level = "Level 6",
                            Module_Code = "BI200212",
                            Module_Description = "I203 Digital Multimedia"
                        },
                        new
                        {
                            ID = 112,
                            Level = "Level 6",
                            Module_Code = "BI200213",
                            Module_Description = "T205 Networks (Cisco ITN)"
                        },
                        new
                        {
                            ID = 113,
                            Level = "Level 6",
                            Module_Code = "BI200214",
                            Module_Description = "T206 Networks (Cisco RSE)"
                        },
                        new
                        {
                            ID = 114,
                            Level = "Level 6",
                            Module_Code = "BI200215",
                            Module_Description = "I209 Industry Placement"
                        },
                        new
                        {
                            ID = 115,
                            Level = "Level 6",
                            Module_Code = "BI200216",
                            Module_Description = "I212 Enterprise Data Management"
                        },
                        new
                        {
                            ID = 116,
                            Level = "Level 6",
                            Module_Code = "BI200217",
                            Module_Description = "I263 Introduction to Finance"
                        },
                        new
                        {
                            ID = 117,
                            Level = "Level 6",
                            Module_Code = "BI200250",
                            Module_Description = "Elective A"
                        },
                        new
                        {
                            ID = 118,
                            Level = "Level 6",
                            Module_Code = "BI200251",
                            Module_Description = "Elective B"
                        },
                        new
                        {
                            ID = 119,
                            Level = "Level 7",
                            Module_Code = "BI300250",
                            Module_Description = "Elective C"
                        },
                        new
                        {
                            ID = 120,
                            Level = "Level 7",
                            Module_Code = "BI300251",
                            Module_Description = "Elective D"
                        },
                        new
                        {
                            ID = 121,
                            Level = "Level 7",
                            Module_Code = "BI300300",
                            Module_Description = "I301 Professional Practice"
                        },
                        new
                        {
                            ID = 122,
                            Level = "Level 7",
                            Module_Code = "BI300301",
                            Module_Description = "I302 Industry Project"
                        },
                        new
                        {
                            ID = 123,
                            Level = "Level 7",
                            Module_Code = "BI300302",
                            Module_Description = "D301 Software Engineering"
                        },
                        new
                        {
                            ID = 124,
                            Level = "Level 7",
                            Module_Code = "BI300303",
                            Module_Description = "D303 Mobile Application Development"
                        },
                        new
                        {
                            ID = 125,
                            Level = "Level 7",
                            Module_Code = "BI300304",
                            Module_Description = "D311 Advanced Database Concepts"
                        },
                        new
                        {
                            ID = 126,
                            Level = "Level 7",
                            Module_Code = "BI300305",
                            Module_Description = "I303 Managerial Practice"
                        },
                        new
                        {
                            ID = 127,
                            Level = "Level 7",
                            Module_Code = "BI300306",
                            Module_Description = "I321 Advanced Systems Analysis"
                        },
                        new
                        {
                            ID = 128,
                            Level = "Level 7",
                            Module_Code = "BI300307",
                            Module_Description = "I309 Special Topic"
                        },
                        new
                        {
                            ID = 129,
                            Level = "Level 7",
                            Module_Code = "BI300308",
                            Module_Description = "T301 Network Design"
                        },
                        new
                        {
                            ID = 130,
                            Level = "Level 7",
                            Module_Code = "BI300309",
                            Module_Description = "T311 System Administration"
                        },
                        new
                        {
                            ID = 131,
                            Level = "Level 7",
                            Module_Code = "BI300310",
                            Module_Description = "T302 Cisco Scaling and Connecting Networks"
                        },
                        new
                        {
                            ID = 132,
                            Level = "Level 7",
                            Module_Code = "BI300312",
                            Module_Description = "I304 Data Analytics and Intelligence"
                        },
                        new
                        {
                            ID = 133,
                            Level = "Level 7",
                            Module_Code = "BI300313",
                            Module_Description = "I311 Advanced Web Solutions"
                        },
                        new
                        {
                            ID = 134,
                            Level = "Level 7",
                            Module_Code = "BI300314",
                            Module_Description = "I367 Advanced Project Management"
                        },
                        new
                        {
                            ID = 135,
                            Level = "Level 7",
                            Module_Code = "BI300315",
                            Module_Description = "T312 Network Security"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
